# Generated by Django 5.2.7 on 2025-10-11 12:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('formatted_address', models.TextField(blank=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('location_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('emergency', 'Emergency'), ('current', 'Current Location'), ('other', 'Other')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geolocation_locations',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('entrance_instructions', models.TextField(blank=True)),
                ('has_ambulance_bay', models.BooleanField(default=False)),
                ('emergency_entrance_coordinates', models.CharField(blank=True, max_length=100)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_location', to='geolocation.location')),
            ],
            options={
                'db_table': 'geolocation_hospital_locations',
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='geolocation_latitud_1a62f4_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user', 'is_primary'], name='geolocation_user_id_6e76fe_idx'),
        ),
    ]
