# Generated by Django 5.2.7 on 2025-11-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyhospitalcommunication',
            name='alert_reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='emergencyhospitalcommunication',
            name='emergency_alert_id',
            field=models.CharField(db_index=True, editable=False, max_length=36),
        ),
    ]
