# Generated by Django 5.2.7 on 2025-11-17 08:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_communication', '0002_alter_emergencyhospitalcommunication_alert_reference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='BPM', null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=4, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='SpO2 percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, help_text='Blood glucose level', max_digits=5, null=True)),
                ('gcs_eyes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('gcs_verbal', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gcs_motor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('gcs_total', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('symptoms', models.JSONField(default=list, help_text='List of reported symptoms')),
                ('injuries', models.JSONField(default=list, help_text='List of observed injuries')),
                ('injury_mechanism', models.TextField(blank=True, help_text='How the injury occurred')),
                ('pain_level', models.CharField(blank=True, choices=[('0', '0 - No Pain'), ('1-3', '1-3 - Mild'), ('4-6', '4-6 - Moderate'), ('7-10', '7-10 - Severe')], max_length=10)),
                ('pain_location', models.TextField(blank=True, help_text='Location of pain')),
                ('medications', models.TextField(blank=True, help_text='Current medications')),
                ('allergies', models.TextField(blank=True, help_text='Known allergies')),
                ('medical_history', models.TextField(blank=True, help_text='Past medical history')),
                ('last_meal', models.TextField(blank=True, help_text='When patient last ate/drank')),
                ('condition', models.CharField(choices=[('critical', 'Critical'), ('serious', 'Serious'), ('stable', 'Stable'), ('guarded', 'Guarded')], default='stable', max_length=20)),
                ('consciousness', models.CharField(choices=[('alert', 'Alert'), ('verbal', 'Responds to Verbal'), ('pain', 'Responds to Pain'), ('unresponsive', 'Unresponsive')], default='alert', max_length=20)),
                ('breathing', models.CharField(choices=[('normal', 'Normal'), ('labored', 'Labored'), ('shallow', 'Shallow'), ('absent', 'Absent')], default='normal', max_length=20)),
                ('circulation', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Weak Pulse'), ('absent', 'Absent Pulse'), ('irregular', 'Irregular')], default='normal', max_length=20)),
                ('triage_category', models.CharField(choices=[('immediate', 'Immediate (Red)'), ('delayed', 'Delayed (Yellow)'), ('minor', 'Minor (Green)'), ('expectant', 'Expectant (Black)')], default='immediate', max_length=20)),
                ('treatment_provided', models.TextField(blank=True, help_text='First aid treatments provided')),
                ('medications_administered', models.TextField(blank=True, help_text='Medications given by first aider')),
                ('assessment_notes', models.TextField(blank=True, help_text='Additional assessment notes')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for hospital care')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assessment', to='hospital_communication.emergencyhospitalcommunication')),
            ],
            options={
                'db_table': 'patient_assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
