# Generated by Django 5.2.7 on 2025-12-12 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_communication', '0003_patientassessment'),
        ('hospitals', '0003_alter_hospital_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('analytics', 'Analytics Report'), ('performance', 'Performance Report'), ('emergency', 'Emergency Communications Report')], default='summary', max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Date Range')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('statistics', models.JSONField(default=dict, help_text='Report statistics and metrics')),
                ('breakdowns', models.JSONField(default=dict, help_text='Data breakdowns by category')),
                ('communications', models.JSONField(default=list, help_text='Summary of communications')),
                ('recommendations', models.JSONField(default=list, help_text='Generated recommendations')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hospital_reports/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='hospital_reports/csv/')),
                ('is_generated', models.BooleanField(default=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'hospital_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'created_at'], name='hospital_re_hospita_0ad205_idx'), models.Index(fields=['report_type', 'period'], name='hospital_re_report__222c02_idx')],
            },
        ),
    ]
