# Generated by Django 5.2.7 on 2025-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('hospital_admin', 'Hospital Admin'), ('organization_admin', 'Organization Admin'), ('first_aider', 'First Aider'), ('hospital_staff', 'Hospital Staff')], default='first_aider', max_length=20),
        ),
    ]
