# Generated by Django 5.2.7 on 2025-10-13 18:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('accident', 'Accident'), ('cardiac', 'Cardiac Arrest'), ('trauma', 'Trauma'), ('respiratory', 'Respiratory Distress'), ('pediatric', 'Pediatric Emergency'), ('other', 'Other')], default='medical', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('current_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('current_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('hospital_selected', 'Hospital Selected'), ('en_route', 'En Route to Hospital'), ('arrived', 'Arrived at Hospital'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts', to='geolocation.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_method', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS'), ('push', 'Push Notification'), ('auto', 'Automatic')], default='auto', max_length=20)),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('is_successful', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='emergencies.emergencyalert')),
            ],
            options={
                'db_table': 'alert_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('location_updates_count', models.PositiveIntegerField(default=0)),
                ('websocket_channel', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='emergencies.emergencyalert')),
            ],
            options={
                'db_table': 'emergency_sessions',
            },
        ),
        migrations.CreateModel(
            name='EmergencyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('created', 'Alert Created'), ('verified', 'Alert Verified'), ('location_updated', 'Location Updated'), ('status_changed', 'Status Changed'), ('hospital_assigned', 'Hospital Assigned'), ('ambulance_dispatched', 'Ambulance Dispatched'), ('eta_updated', 'ETA Updated'), ('cancelled', 'Alert Cancelled'), ('completed', 'Alert Completed')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='emergencies.emergencyalert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['alert_id'], name='emergency_a_alert_i_fdc901_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['user', 'created_at'], name='emergency_a_user_id_2c7f20_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['status', 'is_active'], name='emergency_a_status_aaa8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['created_at'], name='emergency_a_created_883a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencysession',
            index=models.Index(fields=['session_id'], name='emergency_s_session_db524d_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencysession',
            index=models.Index(fields=['is_active'], name='emergency_s_is_acti_66a4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyupdate',
            index=models.Index(fields=['alert', 'created_at'], name='emergency_u_alert_i_92f1e8_idx'),
        ),
    ]
