# Generated by Django 5.2.7 on 2025-10-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert_id',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='emergency_type',
            field=models.CharField(choices=[('medical', 'Medical Emergency'), ('accident', 'Accident'), ('cardiac', 'Cardiac Arrest'), ('trauma', 'Trauma'), ('respiratory', 'Respiratory Distress'), ('pediatric', 'Pediatric Emergency'), ('other', 'Other')], default='medical', max_length=30),
        ),
    ]
