# Generated by Django 5.2.7 on 2025-10-13 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hospital_type', models.CharField(choices=[('public', 'Public Hospital'), ('private', 'Private Hospital'), ('mission', 'Mission Hospital'), ('clinic', 'Clinic'), ('specialized', 'Specialized Center')], default='public', max_length=20)),
                ('level', models.CharField(choices=[('level_1', 'Level 1 - Basic'), ('level_2', 'Level 2 - General'), ('level_3', 'Level 3 - Specialized'), ('level_4', 'Level 4 - Regional Referral'), ('level_5', 'Level 5 - National Referral'), ('level_6', 'Level 6 - International')], default='level_2', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('place_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('mfl_code', models.CharField(blank=True, help_text='Ministry of Health Facility Code', max_length=20)),
                ('is_operational', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('accepts_emergencies', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='geolocation.hospitallocation')),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.PositiveIntegerField(help_text='Response time in seconds')),
                ('accepted_patient', models.BooleanField(default=False)),
                ('reason_for_rejection', models.TextField(blank=True)),
                ('beds_available_at_response', models.PositiveIntegerField(default=0)),
                ('emergency_beds_available_at_response', models.PositiveIntegerField(default=0)),
                ('alert_received_at', models.DateTimeField()),
                ('response_sent_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'emergency_responses',
                'ordering': ['-response_sent_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('available_beds', models.PositiveIntegerField(default=0)),
                ('emergency_beds_total', models.PositiveIntegerField(default=0)),
                ('emergency_beds_available', models.PositiveIntegerField(default=0)),
                ('icu_beds_total', models.PositiveIntegerField(default=0)),
                ('icu_beds_available', models.PositiveIntegerField(default=0)),
                ('average_wait_time', models.PositiveIntegerField(default=0, help_text='Average wait time in minutes')),
                ('emergency_wait_time', models.PositiveIntegerField(default=0, help_text='Emergency department wait time')),
                ('doctors_available', models.PositiveIntegerField(default=0)),
                ('nurses_available', models.PositiveIntegerField(default=0)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('capacity_status', models.CharField(choices=[('low', 'Low Capacity'), ('moderate', 'Moderate Capacity'), ('high', 'High Capacity'), ('full', 'At Capacity'), ('overflow', 'Overflow')], default='moderate', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('next_update_expected', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='hospitals.hospital')),
            ],
            options={
                'verbose_name_plural': 'Hospital capacities',
                'db_table': 'hospital_capacities',
            },
        ),
        migrations.CreateModel(
            name='HospitalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('staff_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('facilities_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('emergency_care_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_title', models.CharField(blank=True, max_length=100)),
                ('review_text', models.TextField(blank=True)),
                ('was_emergency', models.BooleanField(default=False)),
                ('emergency_type', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hospitals.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('trauma', 'Trauma Center'), ('cardiac', 'Cardiac Care'), ('pediatric', 'Pediatric Care'), ('maternity', 'Maternity'), ('surgical', 'Surgical Services'), ('icu', 'Intensive Care Unit'), ('emergency', 'Emergency Department'), ('orthopedic', 'Orthopedic'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('burn_unit', 'Burn Unit'), ('psychiatric', 'Psychiatric'), ('rehabilitation', 'Rehabilitation')], max_length=50)),
                ('capability_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('specialized', 'Specialized')], default='basic', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='hospitals.hospital')),
            ],
            options={
                'verbose_name_plural': 'Hospital specialties',
                'db_table': 'hospital_specialties',
            },
        ),
        migrations.CreateModel(
            name='HospitalWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('emergency_opens_at', models.TimeField(blank=True, null=True)),
                ('emergency_closes_at', models.TimeField(blank=True, null=True)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('is_emergency_24_hours', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='hospitals.hospital')),
            ],
            options={
                'verbose_name_plural': 'Hospital working hours',
                'db_table': 'hospital_working_hours',
            },
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name'], name='hospitals_name_9e93ed_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['hospital_type'], name='hospitals_hospita_2fee4a_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['level'], name='hospitals_level_7b084f_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_operational', 'accepts_emergencies'], name='hospitals_is_oper_d0bd84_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['hospital', 'response_sent_at'], name='emergency_r_hospita_aa2667_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalrating',
            index=models.Index(fields=['hospital', 'overall_rating'], name='hospital_ra_hospita_8272fb_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalrating',
            index=models.Index(fields=['was_emergency'], name='hospital_ra_was_eme_f76ac0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalspecialty',
            unique_together={('hospital', 'specialty')},
        ),
        migrations.AlterUniqueTogether(
            name='hospitalworkinghours',
            unique_together={('hospital', 'day')},
        ),
    ]
