# Generated by Django 5.2.7 on 2025-12-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        ('hospitals', '0002_hospital_address_hospital_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital', to='geolocation.hospitallocation'),
        ),
    ]
